apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: s-deploy
  name: s-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: s-deploy
    spec:
      containers:
      - image: sahil0824/flask-pvc:latest
        name: sahil0824
        resources: {}
        volumeMounts:
        - mountPath: /app/data/
          name: flask-storage
      volumes:
      - name: flask-storage
        persistentVolumeClaim:
          claimName: flask-pvc
status: {}
