apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: s-deploy
  name: s-deploy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: s-deploy
  type: NodePort
status:
  loadBalancer: {}
